"""Supervisorly command line.

Every pipeline stage is independently runnable from here (architecture §7), so the
tool is debuggable and portable. Shipped commands: ``init-db``, ``version``,
``scan`` (demo + live, plan-driven and named-target inputs, D-066), ``map-field``
(the subject-map stage, D-066), ``studio`` (the Scan Studio plan wizard, D-067),
``ingest-page`` (the browser seam, D-064), ``ingest-md`` (the human rung's return
path, D-043), ``reexport`` (dashboard rebuild from the persisted store, D-029) and
``pace`` (the social pacing gate, D-065).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from . import PRODUCT_NAME, __version__
from .discover import ror as ror_mod
from .discover import sitecrawl
from .fetch import pool as pool_mod
from .model.db import open_db


def cmd_version(_args: argparse.Namespace) -> int:
    print(f"{PRODUCT_NAME} {__version__}")
    return 0


def cmd_init_db(args: argparse.Namespace) -> int:
    path = Path(args.db)
    # sqlite3 can't create the parent directory itself — do it here so a path
    # like output/run.sqlite works on a first run.
    if path.parent != Path("") and not path.parent.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
    open_db(path).close()
    print(f"initialised {path}")
    return 0


def _read_staging_text(file: Path) -> str | None:
    """Read a hand-produced staging file, or print why it is unusable and return ``None``.

    PowerShell 5.1's ``>`` and ``Out-File`` default to UTF-16 with a BOM on Windows, which is
    by far the most common way this file arrives — so it is decoded, not rejected.
    """
    raw = file.read_bytes()
    if raw.startswith((b"\xff\xfe", b"\xfe\xff")):
        text = raw.decode("utf-16")
    else:
        try:
            text = raw.decode("utf-8-sig")     # utf-8-sig also strips a leading BOM
        except UnicodeDecodeError:
            print(f"staging file {file} is not UTF-8 text - re-save it as UTF-8 "
                  f"(e.g. Out-File -Encoding utf8) and retry.")
            return None
    text = text.lstrip("﻿")               # a leading BOM is not content
    if not text.strip():
        print(f"staging file {file} is empty - nothing to ingest.")
        return None
    return text


def cmd_ingest_md(args: argparse.Namespace) -> int:
    """The RECEIVING half of the human rung (D-043/D-051).

    Every ``human_prompt`` the dashboard hands out — generated by ``extract.chrome_prompt``,
    which emits its required shape through ``extract.md_grammar`` — asks Claude for Chrome to
    return claims as ``## field:`` Markdown blocks. Nothing read that grammar back.
    ``ingest.ingest_md`` was written for exactly this and called by no command, so the student
    could do the walled-page work in their own browser and then have nowhere to put the answer:
    ``ingest-page`` takes raw page *text* and runs the deterministic extractors over it, which
    is a different rung. A blocked field that offers a prompt and accepts no answer is the dead
    end D-070 forbids.

    Human-returned data is not privileged: each block goes through ``record_claim`` and the
    same D-010 quote gate as a fetched one, and is stamped ``human-assisted (Claude for
    Chrome)`` so a reader can always tell how it arrived.
    """
    from .extract.md_grammar import MDParseError
    from .ingest import ingest_md

    file = Path(args.file)
    if not file.is_file():
        print(f"markdown file not found: {file}")
        return 2
    text = _read_staging_text(file)
    if text is None:
        return 2
    db = Path(args.db)
    if not db.is_file():
        print(f"database not found: {db} - run a scan first.")
        return 2
    conn = open_db(db)
    try:
        try:
            res = ingest_md(conn, text)
        except MDParseError as exc:
            # Fail loud and point at the grammar (D-002): a half-parsed paste that silently
            # recorded two of five fields would leave three gaps looking answered.
            print(f"could not parse {file}: {exc}")
            print("Expected the '## field:' Markdown shape from the dashboard's prompt - "
                  "paste the model's reply verbatim, including its header block.")
            return 2
    finally:
        conn.close()
    kind, ref = res["entity"]
    line = f"ingested {res['recorded']} claim(s) for {kind} {ref} from {file}"
    if res["rejected"]:
        # A quote that is not in the snapshot is rejected here exactly as it would be from a
        # fetch — say which, so the student can fix that one block rather than re-do the page.
        line += f"; REJECTED {len(res['rejected'])}: " + "; ".join(res["rejected"])
    print(line)
    print("run 'supervisorly reexport' to rebuild the dashboard with these values.")
    return 0


def cmd_ingest_page(args: argparse.Namespace) -> int:
    """Browser ingest seam (D-064): store agent-extracted page TEXT as a snapshot.

    The agent saves the in-page JS extractor's output to a staging file and calls
    this command; it handles only paths, byte counts, and the one-line result —
    raw HTML/DOM never enters the agent's context.

    Store-only by default; with ``--entity <kind:ref>`` + ``--run <run_id>`` it also runs
    the consumer half (``fetch.browser_fill``): the pipeline's own extractors fill the
    entity's signal fields from the snapshot, its awaiting_human gap tasks close, and the
    run status is recomputed (D-049)."""
    from urllib.parse import urlparse

    from .fetch.browser_rung import ingest_page

    url = (args.url or "").strip()
    parsed = urlparse(url)
    if parsed.scheme not in ("http", "https") or not parsed.netloc:
        print(f"invalid --url {args.url!r}: pass the FINAL http(s) page url.")
        return 2
    file = Path(args.file)
    if not file.is_file():
        print(f"staging file not found: {file}")
        return 2
    text = _read_staging_text(file)
    if text is None:
        return 2

    # ── optional fill mode: --entity <kind:ref> + --run <run_id>, always together ──
    entity_kind = entity_ref = None
    if (args.entity is None) != (args.run is None):
        print("--entity and --run must be given together (fill mode), or neither "
              "(store-only).")
        return 2
    if args.entity is not None:
        kind, sep, ref = args.entity.partition(":")
        kind = {"professor": "person"}.get(kind.strip(), kind.strip())
        ref = ref.strip()
        if not sep or not kind or not ref:
            print(f"invalid --entity {args.entity!r}: expected <kind>:<ref> "
                  f"(e.g. professor:a1234567890).")
            return 2
        if kind != "person":
            print(f"invalid --entity {args.entity!r}: kind must be 'professor' (or "
                  f"'person') - deep-dive targets are people.")
            return 2
        entity_kind, entity_ref = kind, ref

    db = Path(args.db)
    if db.parent != Path("") and not db.parent.exists():
        db.parent.mkdir(parents=True, exist_ok=True)   # same first-run rule as init-db
    snap_root = Path(args.snap_root) if args.snap_root else db.parent / ".cache" / "snaps"
    conn = open_db(db)
    try:
        if entity_kind is None:
            res = ingest_page(conn, snap_root, final_url=url, text=text)
            # ASCII-only console output (cp1252 consoles can't encode arrows - _write_result)
            print(f"ingested {res['bytes']} bytes -> snap {res['snapshot_hash'][:12]} "
                  f"source {res['source_id']}")
            return 0

        from . import pipeline
        from .fetch.browser_fill import fill_from_browser_page
        from .model import claims, runs

        if runs.get_run(conn, args.run) is None:
            print(f"unknown --run {args.run!r}: no such run in {db}.")
            return 2
        known = claims.claims_for(conn, entity_kind, entity_ref) or any(
            t["target_ref"] == entity_ref for t in runs.tasks_for_run(conn, args.run))
        if not known:
            print(f"unknown --entity {args.entity!r}: {entity_ref} has no claims and is "
                  f"not a target of run {args.run}.")
            return 2
        res = fill_from_browser_page(
            conn, snap_root, run_id=args.run, entity_kind=entity_kind,
            entity_id=entity_ref, final_url=url, text=text)
    finally:
        conn.close()
    filled = " ".join(f"{f}={res['fields'][f]}" for f in pipeline.BROWSER_FILL_FIELDS)
    line = (f"ingested {res['bytes']} bytes -> snap {res['snapshot_hash'][:12]} "
            f"source {res['source_id']}; filled {filled}; "
            f"{res['tasks_closed']} gap(s) closed; run {res['run_status']}")
    if res["rejected"]:
        why = "; ".join(f"{f}: {r}" for f, r in res["rejected"].items())
        line += f"; REJECTED {why} - gap left open"
    print(line)
    return 0


def cmd_reexport(args: argparse.Namespace) -> int:
    """Rebuild the dashboard from the persisted store — no fetching (D-029).

    This is the post-fill step of the browser recipe: after ``ingest-page --entity ...``
    closes a gap, regenerate the dashboard so it shows the filled values. Targets are
    reconstructed from the persisted claims (the store keeps ids, not display names, so a
    re-exported dashboard names professors by id — the full named view comes from a
    ``scan --resume`` re-export)."""
    from . import pipeline

    db = Path(args.db)
    if not db.is_file():
        print(f"database not found: {db} - run a scan first.")
        return 2
    conn = open_db(db)
    try:
        pids = [r["entity_id"] for r in conn.execute(
            "SELECT DISTINCT entity_id FROM claim WHERE entity_kind='person' "
            "ORDER BY entity_id")]
    finally:
        conn.close()
    if not pids:
        print(f"no professor claims in {db} - nothing to re-export.")
        return 2
    result = pipeline.reexport(db, [{"id": pid} for pid in pids],
                               optout_path=args.optout)
    return _write_result(result, Path(args.out), "reexport")


def cmd_pace(args: argparse.Namespace) -> int:
    """Social pacing gate (D-065): check/abort/reset before every browser page."""
    from .ethics import pacing

    if args.reset:
        pacing.reset(None if args.reset == "all" else args.reset, state_path=args.state)
        print(f"RESET host={args.reset}")
        return 0
    if not args.host:
        print("pace needs --host <host> (unless --reset is given).")
        return 2
    if args.abort is not None:
        pacing.abort(args.host, args.abort, state_path=args.state)
        print(f"ABORTED host={args.host} reason={args.abort or 'challenge'}")
        return 0
    res = pacing.check(args.host, state_path=args.state)
    verdict = "ALLOW" if res["allowed"] else "DENY"
    print(f"{verdict} host={args.host} wait={res['wait_seconds']}s reason={res['reason']}")
    return 0 if res["allowed"] else 3


def _warn_if_committable(out: Path) -> None:
    """D-005 guard: scan output holds personal data and must never be committed.

    When the resolved --out path sits inside a git work tree and neither it nor its
    sibling .json is covered by git-ignore rules, warn loudly BEFORE writing. Warn only —
    legitimate out-of-repo paths must keep working, and a missing git binary (or any git
    failure) is a clean no-op."""
    import subprocess

    target = out.resolve()
    cwd = target.parent
    while not cwd.is_dir() and cwd != cwd.parent:
        cwd = cwd.parent

    def _ignored(p: Path) -> bool | None:
        """True/False from git; None when git can't answer (absent, or not a work tree)."""
        try:
            r = subprocess.run(["git", "-C", str(cwd), "check-ignore", "-q", str(p)],
                               capture_output=True, timeout=10)
        except (OSError, subprocess.SubprocessError):
            return None
        return {0: True, 1: False}.get(r.returncode)   # 128 = not a work tree → no opinion

    ignored = [_ignored(target), _ignored(target.with_suffix(".json"))]
    if not all(i is False for i in ignored):
        return   # ignored, or git/repo unavailable → silent
    # ASCII-only: the default Windows console codec (cp1252) can't encode an em-dash and
    # would crash the command before the files are written (see _write_result).
    print(f"WARNING (D-005): {target} is inside a git work tree and is NOT git-ignored. "
          "Scan output contains personal data and must never be committed. "
          "Write under an ignored directory (e.g. output/) or add the path to .gitignore.",
          file=sys.stderr)


def _write_result(result: dict, out: Path, label: str) -> int:
    """Write the dashboard + sibling JSON and print an ASCII-safe status line."""
    import json
    _warn_if_committable(out)
    if out.parent != Path("") and not out.parent.exists():
        out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(result["html"], encoding="utf-8")
    out.with_suffix(".json").write_text(
        json.dumps(result["export"], ensure_ascii=False, indent=2), encoding="utf-8")
    n = len(result["export"]["professors"])
    # Surface the opt-out suppression count so a smaller professor list is never misread as
    # a coverage gap (D-023/D-046).
    opted = (result.get("stats") or {}).get("opted_out") or 0
    opt_note = f", {opted} opted out" if opted else ""
    # ASCII-only console output — the default Windows console codec (cp1252) can't encode a
    # Unicode arrow, which would crash the command after the files were already written.
    print(f"scanned {n} professors ({label}{opt_note}) -> {out} "
          f"(+ {out.with_suffix('.json').name})")
    return 0


def cmd_studio(args: argparse.Namespace) -> int:
    """Scan Studio (D-067): render a ``map-field`` subject map as the self-contained,
    offline plan wizard. Fails loud (exit 2) on a missing/invalid map file (D-002)."""
    import json

    from .export.studio import build_studio

    p = Path(args.map)
    if not p.is_file():
        print(f"subject map not found: {p} - run `supervisorly map-field` first.")
        return 2
    try:
        smap = json.loads(p.read_text(encoding="utf-8"))
    except ValueError as exc:
        print(f"invalid subject-map JSON in {p}: {exc}")
        return 2
    if not isinstance(smap, dict) or not isinstance(smap.get("groups"), list):
        print(f"{p} is not a subject map (expected a JSON object with a 'groups' list) - "
              "produce one with `supervisorly map-field`.")
        return 2

    out = Path(args.out)
    _warn_if_committable(out)                       # D-005 guard, same as scan --out
    if out.parent != Path("") and not out.parent.exists():
        out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build_studio(smap), encoding="utf-8")
    n_topics = sum(len(g.get("topics") or []) for g in smap["groups"] if isinstance(g, dict))
    # ASCII-only console output (cp1252 convention — see _write_result)
    print(f"studio wrote {n_topics} topics in {len(smap['groups'])} groups -> {out}")
    return 0


def cmd_map_field(args: argparse.Namespace) -> int:
    """Subject-map stage (D-066): field free text -> grouped OpenAlex topic map JSON.

    API-derived only (D-038); the user multi-selects from the written map and the selected
    topic IDs become a plan's ``resolved_topic_ids``. Requires a contact email (polite pool),
    exactly like a live scan."""
    import json
    import os

    from . import preflight

    email = args.email or preflight.contact_email(os.environ)
    try:
        preflight.require_credentials({preflight.CONTACT_EMAIL_ENV: email or ""})
    except preflight.MissingCredentials as exc:
        print(str(exc))
        return 2

    from .discover.subjects import subject_map
    from .fetch.transport import httpx_transport

    transport = httpx_transport(user_agent=f"SupervisorlyBot/0.1 (mailto:{email})")
    smap = subject_map(args.field, transport, email=email,
                       key=(args.openalex_key or os.environ.get(preflight.OPENALEX_KEY_ENV)))
    out = Path(args.out)
    if out.parent != Path("") and not out.parent.exists():
        out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(smap, ensure_ascii=False, indent=2), encoding="utf-8")
    n_topics = sum(len(g["topics"]) for g in smap["groups"])
    # ASCII-only console output (cp1252 convention — see _write_result)
    suffix = " (PARTIAL)" if smap["truncated"] else ""
    print(f"mapped {n_topics} topics in {len(smap['groups'])} groups{suffix} -> {out}")
    if smap.get("relaxed_from"):
        print(f"note: no exact topics for '{smap['relaxed_from']}'; broadened to per-word "
              "search over the OpenAlex topic index")
    return 0


# Keys a Scan Studio / conversational plan JSON must carry (D-066). A plan missing any of
# these is rejected loudly with the full expected list, never silently defaulted.
# (This previously cited D-002, which is about v1 targeting any country — the fail-loud rule
# is a build principle from IMPLEMENTATION_GOAL.md, not a numbered decision.)
PLAN_REQUIRED_KEYS = ("intent_kind", "country", "resolved_topic_ids", "field",
                      "university_mode", "universities")

# Valid enum values a plan may carry — mirrors the argparse choices of the overriding flags.
#: There is deliberately NO cap on how many fields a plan may carry.
#:
#: There was one (6), and it was wrong: it refused a student's input to solve a cost problem
#: that belongs to the cost layer. Someone working across six areas is exactly the person this
#: tool is for, and "remove one to add another" makes them choose which part of their own
#: research to hide. The real limiters stayed where they belong — the §5.2 per-IP throttle
#: bounds spend, and /api/map now takes every phrasing in ONE request (B-001) so a wide search
#: costs one unit rather than one per phrasing.
#:
#: What IS still enforced is shape: entries must be non-blank strings. A blank field means the
#: intent was mangled upstream, and that still fails loud.
PLAN_MAX_FIELDS = None

PLAN_UNIVERSITY_MODES = ("all", "prioritise", "only")
PLAN_INTENT_KINDS = ("training", "pre_master", "pre_phd", "mentor", "master", "phd",
                     "postdoc")


def _target_spec_errors(specs, key: str = "targets") -> list[str]:
    """Validation errors for a ``--targets`` / plan-carried targets list (D-002).

    Every entry must be an OpenAlex author URL string or a ``{"name": non-empty str,
    "affiliation": str?}`` object — a numeric name would be searched verbatim (confidently
    resolving whoever OpenAlex's top hit for "42" is), and a non-string affiliation crashes
    the author lookup with an AttributeError traceback instead of a clear message."""
    if not isinstance(specs, list):
        return [f"'{key}' must be a list, got {type(specs).__name__}"]
    errors: list[str] = []
    for i, e in enumerate(specs):
        if isinstance(e, str):
            continue
        if isinstance(e, dict):
            name = e.get("name")
            if not isinstance(name, str) or not name.strip():
                errors.append(f"{key}[{i}]: 'name' must be a non-empty string, got {name!r}")
            affiliation = e.get("affiliation")
            if affiliation is not None and not isinstance(affiliation, str):
                errors.append(f"{key}[{i}]: 'affiliation' must be a string, got "
                              f"{type(affiliation).__name__}")
            continue
        errors.append(f"{key}[{i}] must be an OpenAlex author URL string or a "
                      f'{{"name": ..., "affiliation": ...}} object, got {e!r}')
    return errors


def _plan_value_errors(data: dict) -> list[str]:
    """Type + enum checks on a plan's VALUES (key presence is checked separately, D-002).

    A mangled value must fail loud, never silently mangle: ``list("Uni")`` would otherwise
    become three one-letter "universities" (scanning nothing, misread as a coverage gap) and
    ``list("T10001")`` a list of characters. Enum typos are worse — a plan's
    ``university_mode: "onyl"`` would silently INVERT the asked-for scope ("only these" ->
    the whole country). Case is significant: ``"ONLY"`` is rejected, never quietly
    normalised — a scope decision is never silently rewritten."""
    errors: list[str] = []

    def check_str_list(key: str) -> None:
        v = data.get(key)
        if v is None:
            return
        if not isinstance(v, list) or not all(isinstance(x, str) for x in v):
            errors.append(f"'{key}' must be a list of strings, got "
                          f"{type(v).__name__}")

    check_str_list("resolved_topic_ids")
    check_str_list("universities")
    check_str_list("fields")
    # A plan file may carry the institution pool too (`--plan` and the web wizard both put it
    # there). Validated on the same terms as `university_mode`: a typo here silently narrows
    # the scan to nothing and then fails OPEN to every type — the opposite of what was asked,
    # arrived at quietly.
    itypes = data.get("institution_types")
    if itypes is not None and itypes != "all":
        if not isinstance(itypes, list) or not all(isinstance(x, str) for x in itypes):
            errors.append("'institution_types' must be a list of ROR types, or 'all'")
        else:
            unknown = [t for t in itypes if t.strip().lower() not in ror_mod.KNOWN_TYPES]
            if unknown:
                errors.append(f"'institution_types' has unknown value(s): "
                              f"{', '.join(unknown)} — valid: "
                              f"{', '.join(ror_mod.KNOWN_TYPES)} (or 'all')")
    # A student rarely has exactly one way to say what they work on: "ML", "AI safety" and
    # "NLP" are three doors into overlapping literatures, and making them pick one door first
    # is the tool deciding their scope for them. `fields` carries all of them; `field` remains
    # the single human-readable string every existing consumer already reads, derived from
    # them, so nothing downstream has to learn a new shape.
    fields = data.get("fields")
    if isinstance(fields, list):
        if PLAN_MAX_FIELDS is not None and len(fields) > PLAN_MAX_FIELDS:
            errors.append(f"'fields' accepts at most {PLAN_MAX_FIELDS} entries, "
                          f"got {len(fields)}")
        if any(isinstance(f, str) and not f.strip() for f in fields):
            errors.append("'fields' must not contain blank entries")
    # How many phrasings the student asked the expander to try per field (the step-2 slider).
    # Out-of-range is clamped by the server rather than rejected — a number is a preference,
    # not a claim, and refusing a plan over a slider position would be absurd.
    depth = data.get("variants_per_field")
    if depth is not None and not isinstance(depth, int):
        errors.append(f"'variants_per_field' must be an integer, got {type(depth).__name__}")
    for key in ("country", "university_mode", "intent_kind", "field", "email"):
        v = data.get(key)
        if v is not None and not isinstance(v, str):
            errors.append(f"'{key}' must be a string, got {type(v).__name__}")
    mode = data.get("university_mode")
    if isinstance(mode, str) and mode not in PLAN_UNIVERSITY_MODES:
        errors.append(f"'university_mode' must be one of {', '.join(PLAN_UNIVERSITY_MODES)}, "
                      f"got {mode!r}")
    intent = data.get("intent_kind")
    if isinstance(intent, str) and intent not in PLAN_INTENT_KINDS:
        errors.append(f"'intent_kind' must be one of {', '.join(PLAN_INTENT_KINDS)}, "
                      f"got {intent!r}")
    # A student is rarely looking for exactly one thing — someone may be open to a PhD, a
    # pre-PhD post or a master's. `intent_kinds` carries all of them; `intent_kind` stays as
    # the first element, derived, so every existing consumer keeps reading the shape it
    # already reads. Same "the list is the truth, the scalar is derived" rule as
    # `fields`/`field`.
    check_str_list("intent_kinds")
    kinds = data.get("intent_kinds")
    if isinstance(kinds, list) and all(isinstance(k, str) for k in kinds):
        if not kinds:
            # NOT treated as "search everything": an empty list means the intent was mangled
            # upstream, and a search for nothing is a bug, not a wide search.
            errors.append("'intent_kinds' must not be empty — a search for no level at all "
                          "is a mangled intent, not a wide search")
        bad = [k for k in kinds if k not in PLAN_INTENT_KINDS]
        if bad:
            errors.append(f"'intent_kinds' entries must each be one of "
                          f"{', '.join(PLAN_INTENT_KINDS)}, got "
                          f"{', '.join(repr(b) for b in bad)}")
    if "targets" in data:
        target_errors = _target_spec_errors(data["targets"])
        if target_errors:
            errors.append("invalid 'targets': " + "; ".join(target_errors))
    return errors


def normalize_plan_intents(plan: dict) -> dict:
    """A copy of ``plan`` whose ``intent_kinds`` is canonical and whose ``intent_kind`` is its
    first element.

    One function, called on both entry paths (the CLI and the web API), because "the list is
    the truth and the scalar is derived" is only true if something actually derives it. A
    client that sends a list and a *disagreeing* scalar is corrected here rather than trusted:
    every existing consumer — ``scorer.gates_for``, the worker's log line — reads the scalar,
    so letting the two drift means the run is scored for a level the student did not pick.

    Deliberately NOT merged: the scalar is already the list's first element, so unioning them
    can only ever duplicate. See ``ladder.plan_intents`` for why that rule is written down
    rather than left to judgement.
    """
    from .discover.ladder import plan_intents        # lazy: keeps CLI startup import-light

    kinds = plan_intents(plan)
    if not kinds:
        return dict(plan)          # nothing to derive from; validation reports the gap
    return {**plan, "intent_kinds": kinds, "intent_kind": kinds[0]}


def _load_plan(path: str) -> tuple[dict | None, str | None]:
    """Load + validate a ``--plan`` JSON file; returns ``(plan, None)`` or ``(None, error)``."""
    import json

    p = Path(path)
    if not p.is_file():
        return None, f"plan file not found: {p}"
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except ValueError as exc:
        return None, f"invalid plan JSON in {p}: {exc}"
    if not isinstance(data, dict):
        return None, (f"plan file {p} must hold a JSON object with keys: "
                      f"{', '.join(PLAN_REQUIRED_KEYS)}.")
    missing = [k for k in PLAN_REQUIRED_KEYS if k not in data]
    if missing:
        return None, (f"plan file {p} is missing required key(s): {', '.join(missing)}. "
                      f"Expected a Scan Studio plan with keys: {', '.join(PLAN_REQUIRED_KEYS)}.")
    errors = _plan_value_errors(data)
    if errors:
        return None, f"plan file {p}: " + "; ".join(errors)
    return data, None


def _load_target_specs(path: str) -> tuple[list | None, str | None]:
    """Load a ``--targets`` JSON file: ``[{name, affiliation?}, ...]`` or URL strings."""
    import json

    p = Path(path)
    if not p.is_file():
        return None, f"targets file not found: {p}"
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except ValueError as exc:
        return None, f"invalid targets JSON in {p}: {exc}"
    errors = _target_spec_errors(data)
    if errors:
        return None, (f"targets file {p}: " + "; ".join(errors) +
                      ". Expected a list of {\"name\": ..., \"affiliation\": ...} objects "
                      "or OpenAlex author URL strings.")
    return data, None


def _author_to_target(a: dict) -> dict:
    """An OpenAlex author dict -> a deep-dive target in the ladder's shape (nothing dropped)."""
    from .discover.ladder import _author_url
    url, url_kind = _author_url(a)          # homepage wins, else the ORCID profile (live fix)
    target = {
        "id": a.get("short_id") or (a.get("name") or "unknown").strip().casefold(),
        "name": a.get("name"),
        "url": url,
        "url_kind": url_kind,
        "openalex_id": a.get("openalex_id"),
        "orcid": a.get("orcid"),
        "ror_id": None,
        "institution_names": list(a.get("institution_names") or []),
        "topic_ids": list(a.get("topic_ids") or []),
        "works_count": int(a.get("works_count") or 0),
        "cited_by_count": int(a.get("cited_by_count") or 0),
    }
    if a.get("resolution"):
        target["resolution"] = a["resolution"]
    return target


def _resolve_named_targets(oa, specs: list) -> tuple[list[dict], list[str], list[str]]:
    """Resolve ``--targets`` specs via OpenAlex author search (D-066).

    Returns ``(targets, skipped, notes)``: every spec that resolves to nothing goes into
    ``skipped`` WITH its reason and is reported by the caller — nobody is silently dropped
    (D-022). ``notes`` carries non-fatal honesty lines (e.g. an affiliation that could not be
    confirmed -> ``resolution: unverified`` on the target)."""
    targets: list[dict] = []
    skipped: list[str] = []
    notes: list[str] = []
    for spec in specs:
        markers_before = len(oa.truncated_sources)
        if isinstance(spec, str):
            short_id = spec.rstrip("/").rsplit("/", 1)[-1]
            author = oa.author_by_id(short_id)
            label = spec
        else:
            author = oa.author_search(spec["name"], spec.get("affiliation"))
            label = spec["name"]
        if not author:
            # Distinguish a lookup FAILURE (a truncation-class event — the run is marked
            # PARTIAL, D-037) from a genuine absence (200, empty results — an honest skip).
            if len(oa.truncated_sources) > markers_before:
                skipped.append(f"{label}: OpenAlex lookup FAILED - the run is marked PARTIAL "
                               "in the coverage (likely transient; retry later)")
            else:
                skipped.append(f"{label}: no OpenAlex author match")
            continue
        target = _author_to_target(author)
        targets.append(target)
        if target.get("resolution") == "unverified":
            notes.append(f"{label}: resolved to {author.get('name')} "
                         f"({author.get('openalex_id')}) but the affiliation did not match any "
                         "last-known institution - target marked resolution=unverified.")
    return targets, skipped, notes


def _progress_printer(event: tuple) -> None:
    """``scan --progress``: ONE ASCII line per §4.1 engine event, on stderr (stdout stays
    reserved for the result/warning lines)."""
    phase = event[0]
    if phase == "enumerated":
        line = f"progress: enumerated {event[1]} targets across {event[2]} institutions"
    elif phase == "deep_dive_start":
        line = f"progress: deep-dive 0/{event[1]}"
    elif phase == "deep_dive_progress":
        line = f"progress: deep-dive {event[1]}/{event[2]}"
    elif phase == "partial_warning":
        line = f"progress: PARTIAL - {event[1]}"   # msg is ASCII by construction (pipeline)
    else:                                          # scoring / exported — phase-only events
        line = f"progress: {phase}"
    print(line, file=sys.stderr)


def cmd_serve(args: argparse.Namespace) -> int:
    """Serve the wizard and the API from one local origin — the dashboard AS the CLI.

    Everything `scan` can be told, this page can ask for: scope, institution pools, the
    browser reader, link-following, concurrency, and the comparison against an earlier run.
    It is one command because the three-step version (start the API, generate the page with a
    Python snippet, open the file) is why the product still felt like a CLI with a viewer
    bolted on.

    Loopback only, and that is load-bearing rather than a default: this server reports itself
    as ``local``, which is what unlocks the operator controls the hosted deployment must never
    expose (``--ignore-robots`` spends the reputation of whatever address the scan runs from).
    Binding anywhere else would hand those to a stranger.
    """
    import webbrowser

    from . import webapi
    from .export.webapp import build_webapp
    from .fetch import render as render_mod

    # Same origin as the API it calls, so `api_base` is empty and there is no CORS story.
    page = build_webapp(api_base="")
    server = webapi.build_server(port=args.port, work_root=args.work_root,
                                 local=True, page_html=page)
    url = f"http://127.0.0.1:{args.port}/"
    browser = render_mod.browser_status()
    print(f"Supervisorly is at {url}")
    print(f"  jobs + store   {args.work_root}")
    # State the browser situation at STARTUP, not when a scan silently renders nothing. The
    # page reports it too (GET /api/capabilities), but somebody watching this console should
    # not have to open a tab to find out.
    if browser["available"]:
        print(f"  browser        chromium ready (playwright {browser['version'] or '?'})")
    else:
        print(f"  browser        NOT available - {browser['reason']}")
        print(f"                 fix: {browser['fix']}")
    from .discover import websearch as _ws
    from .extract import llm_client as _llm
    print(f"  page search    {_ws.provider_name() or 'off (no search key configured)'}")
    print(f"  model reading  {'on' if _llm.configured() else 'off (no extraction key)'}")
    print("  operator       robots override available on this local server")
    print("Ctrl+C to stop.")
    if not args.no_open:
        webbrowser.open(url)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nstopped.")
    finally:
        server.server_close()
    return 0


#: sentinel: ``--institution-types`` was given but is not usable (message already printed)
_INVALID = object()


def _parse_institution_types(args: argparse.Namespace):
    """``--institution-types`` -> the plan value, or ``_INVALID`` after printing why.

    ``None`` means "the plan does not choose" (education only). ``"all"`` means every type.
    A misspelling fails LOUD (D-002): silently ignoring it would run an education-only scan
    while the command line says otherwise, and nothing in the output would contradict that.
    """
    raw = getattr(args, "institution_types", None)
    if raw is None:
        return "all" if args.all_institution_types else None
    wanted = [t.strip().lower() for t in str(raw).split(",") if t.strip()]
    if not wanted:
        print("--institution-types was empty; pass one or more of: "
              + ", ".join(ror_mod.KNOWN_TYPES) + " (or 'all').")
        return _INVALID
    if "all" in wanted:
        return "all"
    unknown = [t for t in wanted if t not in ror_mod.KNOWN_TYPES]
    if unknown:
        print(f"unknown --institution-types value(s): {', '.join(unknown)}. "
              f"Valid ROR types: {', '.join(ror_mod.KNOWN_TYPES)} (or 'all').")
        return _INVALID
    if args.all_institution_types:
        # Both flags given and they disagree — one of them is going to be ignored, and
        # guessing which is exactly the silence D-002 forbids.
        print("--all-institution-types and --institution-types "
              f"{','.join(wanted)} conflict; pass only one.")
        return _INVALID
    return wanted


def cmd_scan(args: argparse.Namespace) -> int:
    # Argument validation and the robots banner come FIRST — before any directory is created,
    # any cassette is opened and any request is made. A guard that fires after the work has
    # started is not a guard, and a warning printed after the fetches is a receipt.
    if args.ignore_robots:
        # Loud, before the first request AND before any other guard can pre-empt it, naming
        # who carries the consequence. A setting this consequential should never be
        # discoverable only by reading the flags back.
        print("=" * 72)
        print("robots.txt WILL NOT BE ENFORCED on this scan (--ignore-robots).")
        print("Sites use robots.txt to say 'do not automate me'. Ignoring it gets the")
        print("REQUESTING IP rate-limited and then blocked - on a campus network, yours.")
        print("Provenance still records what robots actually said, per source.")
        print("=" * 72)
    if args.concurrency < 1:
        # fail loud (D-002): 0 or negative would mean "render nothing" while the flag reads
        # as a performance setting.
        print(f"--concurrency must be a positive integer, got {args.concurrency}.")
        return 2
    institution_types = _parse_institution_types(args)
    if institution_types is _INVALID:
        return 2
    previous_export = None
    if getattr(args, "compare_to", None):
        import json
        prev = Path(args.compare_to)
        if not prev.is_file():
            # fail loud (D-002): running anyway would produce an export with no delta, and the
            # student would read "nothing changed" into a comparison that never happened.
            print(f"--compare-to file not found: {prev}")
            return 2
        try:
            previous_export = json.loads(prev.read_text(encoding="utf-8"))
        except (ValueError, OSError) as exc:
            print(f"--compare-to file {prev} is not readable JSON: {exc}")
            return 2
        if not isinstance(previous_export, dict) or "professors" not in previous_export:
            print(f"--compare-to file {prev} is not a Supervisorly export "
                  f"(no 'professors' key) - pass the .json beside a dashboard.")
            return 2

    out = Path(args.out)
    if out.parent != Path("") and not out.parent.exists():
        out.parent.mkdir(parents=True, exist_ok=True)   # for snapshots + the live DB
    snap_root = out.parent / ".cache" / "snaps"

    if args.demo:
        from .demo import demo_fixture
        from .pipeline import run_offline
        tp, targets, plan = demo_fixture()
        # --compare-to works here too: the demo is the path the runbook tells a new user to
        # try first, and a flag that silently does nothing on it teaches the wrong thing.
        result = run_offline(plan, targets, tp, snap_root, optout_path=args.optout,
                             previous_export=previous_export)
        return _write_result(result, out, "demo")

    # ── live scan ──
    import os

    from . import preflight
    # --plan: a Scan Studio / conversational plan JSON supplies the base scope; explicit
    # flags OVERRIDE the plan's values (D-066). Fail loud on a missing/invalid plan (D-002).
    # Loaded BEFORE the credentials check so a Studio plan's own "email" can satisfy it.
    plan_file: dict = {}
    if args.plan:
        plan_file, err = _load_plan(args.plan)
        if err:
            print(err)
            return 2

    email = (args.email or preflight.contact_email(os.environ)
             or plan_file.get("email"))
    try:
        preflight.require_credentials({preflight.CONTACT_EMAIL_ENV: email or ""})
    except preflight.MissingCredentials as exc:
        print(str(exc))
        return 2

    # --targets: named professors to deep-dive directly (resolved below, after the transport).
    # A Studio plan may carry the same list under "targets" — the flag wins when both exist.
    target_specs: list | None = None
    if args.targets:
        target_specs, err = _load_target_specs(args.targets)
        if err:
            print(err)
            return 2
    elif plan_file.get("targets"):
        target_specs = plan_file["targets"]     # shape already validated by _load_plan

    country_in = args.country if args.country is not None else plan_file.get("country")
    field = args.field if args.field is not None else plan_file.get("field")
    topic_ids = list(plan_file.get("resolved_topic_ids") or [])
    if target_specs is None and not country_in:
        print("a live scan needs --country and --field (or a --plan file, or --targets; "
              "or use --demo for the offline demo). See --help.")
        return 2
    if country_in and not field and not topic_ids:
        print("a live scan needs --field (or a --plan with resolved_topic_ids). See --help.")
        return 2

    from .discover.countries import to_country_code
    # --country (or a plan's country) may be a NAME ("Canada") or alpha-2; ROR's filter needs
    # ISO alpha-2. Resolve here, where the plan is built, and fail loud on anything
    # unrecognized (D-002) — never silently query ROR with a filter that matches 0 institutions.
    country_code = None
    if country_in:
        country_code = to_country_code(country_in)
        if not country_code:
            print(f"unrecognized --country {country_in!r}: pass an ISO 3166-1 alpha-2 code "
                  "(e.g. CA) or an English country name (e.g. Canada).")
            return 2

    # The CLI names ONE intent (`--intent`), but a plan file may carry several. Take the
    # file's list when the flag was not given, so `--plan` does not quietly narrow a
    # multi-level search back to its first entry.
    intent_kinds = ([args.intent] if args.intent
                    else (list(plan_file.get("intent_kinds") or [])
                          or [plan_file.get("intent_kind") or "pre_phd"]))
    intent = intent_kinds[0]
    university_mode = args.university_mode or plan_file.get("university_mode") or "all"
    if args.universities is not None:
        universities = [u.strip() for u in args.universities.split(",") if u.strip()]
    else:
        universities = list(plan_file.get("universities") or [])

    from .discover.openalex import OpenAlexClient
    from .fetch.transport import httpx_transport
    from .pipeline import run_live
    openalex_key = args.openalex_key or os.environ.get(preflight.OPENALEX_KEY_ENV)
    plan = normalize_plan_intents(
        {"intent_kind": intent, "intent_kinds": intent_kinds, "country": country_code,
         "field": field, "university_mode": university_mode, "universities": universities,
         "resolved_topic_ids": topic_ids,
         # Explicit flags override the plan file (D-066); a plan that chose types keeps them
         # when the command line stayed silent.
         "institution_types": (institution_types if institution_types is not None
                               else plan_file.get("institution_types")),
         "all_institution_types": args.all_institution_types})
    transport = httpx_transport(user_agent=f"SupervisorlyBot/0.1 (mailto:{email})")

    targets_override = None
    targets_truncated: list[str] = []
    if target_specs is not None:
        oa = OpenAlexClient(transport, email=email, key=openalex_key)
        targets_override, skipped, notes = _resolve_named_targets(oa, target_specs)
        # The author lookups happened on THIS client, not run_live's own — hand its
        # truncation markers (author-search@/author@) to run_live so a lookup FAILURE
        # surfaces as PARTIAL coverage + persisted run counts, exactly like the ladder's
        # own markers (D-037), instead of reading as "none were dropped".
        targets_truncated = list(oa.truncated_sources)
        for line in notes:
            print(f"WARNING: {line}")
        for line in skipped:
            print(f"SKIPPED target {line}")          # reported, never silently dropped (D-022)
        if not targets_override and not country_code:
            print("no --targets entry resolved and no --country ladder was requested - "
                  "nothing to scan.")
            return 2

    if args.shortlist < 1:
        # fail loud (D-002): a 0/negative shortlist would silently deep-dive NOBODY while
        # the export still lists everyone as enumerated-but-unchecked.
        print(f"--shortlist must be a positive integer, got {args.shortlist}.")
        return 2
    if args.max_institutions is not None and args.max_institutions < 1:
        # fail loud (D-002): a 0/negative cap would silently scan NO institution while
        # the plan reads as a full-country scan.
        print(f"--max-institutions must be a positive integer, got {args.max_institutions}.")
        return 2

    result = run_live(
        plan, transport, snap_root, email=email,
        openalex_key=openalex_key,
        db_path=out.parent / "supervisorly.sqlite", optout_path=args.optout, resume=args.resume,
        targets_override=targets_override, targets_truncated=targets_truncated,
        shortlist_size=args.shortlist,
        max_institutions=args.max_institutions,
        progress=_progress_printer if args.progress else None,
        render_all=args.render_all,
        concurrency=args.concurrency,
        obey_robots=not args.ignore_robots,
        crawl=args.crawl,
        previous_export=previous_export,
        use_archive=args.use_archive,
    )
    # sparse-coverage preflight + discovery warnings (D-060) — ASCII-safe by construction
    # (preflight/ladder messages are ASCII-only, like the rest of this console output).
    for w in result["stats"].get("warnings", []):
        print(f"WARNING: {w}")
    return _write_result(result, out, "live")


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="supervisorly", description=__doc__)
    p.add_argument("--version", action="version", version=f"{PRODUCT_NAME} {__version__}")
    sub = p.add_subparsers(dest="command", required=True)

    sub.add_parser("version", help="print the version").set_defaults(func=cmd_version)

    pi = sub.add_parser("init-db", help="create/migrate a scan database")
    pi.add_argument("--db", default="supervisorly.sqlite", help="database path")
    pi.set_defaults(func=cmd_init_db)

    ps = sub.add_parser("scan", help="run a scan and write a dashboard")
    ps.add_argument("--demo", action="store_true", help="run the offline synthetic demo (no keys)")
    ps.add_argument("--out", default="output/dashboard.html", help="dashboard output path")
    ps.add_argument("--optout", default=None,
                    help="path to an optout.txt suppression list (D-023)")
    # live-scan flags
    ps.add_argument("--country", help="country to scan: ISO alpha-2 code or English name "
                                      "(e.g. CA or Canada) (a live scan)")
    ps.add_argument("--field", help="research field / subfield (a live scan)")
    ps.add_argument("--intent", default=None,
                    choices=["training", "pre_master", "pre_phd", "mentor", "master", "phd",
                             "postdoc"],
                    help="what you're looking for (default: pre_phd; overrides --plan)")
    ps.add_argument("--universities", default=None,
                    help="comma-separated universities to prioritise / restrict to")
    ps.add_argument("--university-mode", dest="university_mode", default=None,
                    choices=["all", "prioritise", "only"],
                    help="how to use --universities (default: all; overrides --plan)")
    ps.add_argument("--plan", default=None,
                    help="a Scan Studio plan JSON (D-066): supplies the scan scope; explicit "
                         "flags override its values")
    ps.add_argument("--targets", default=None,
                    help="a JSON file of named professors ([{name, affiliation?}] or OpenAlex "
                         "author URLs) to deep-dive directly (D-066)")
    ps.add_argument("--email", default=None,
                    help="contact email for the OpenAlex polite pool "
                         "(or set SUPERVISORLY_CONTACT_EMAIL)")
    ps.add_argument("--openalex-key", dest="openalex_key", default=None,
                    help="optional OpenAlex premium key (higher limits)")
    ps.add_argument("--resume", action="store_true",
                    help="reuse prior state; skip already-completed targets (cheap re-scan)")
    ps.add_argument("--progress", action="store_true",
                    help="print one ASCII progress line per scan phase to stderr "
                         "(enumerated / deep-dive i/k / scoring / exported); "
                         "default is silent")
    ps.add_argument("--shortlist", type=int, default=40, metavar="N",
                    help="deep-dive only the top N discovered professors by topic fit "
                         "(D-056; default 40). The rest stay listed, unchecked. Named "
                         "--targets always deep-dive.")
    ps.add_argument("--max-institutions", dest="max_institutions", type=int, default=None,
                    metavar="N",
                    help=f"how many institutions to scan (default "
                         f"{ror_mod.DEFAULT_WANT}). This drives how many pages are FETCHED "
                         f"from ROR, not just a slice afterwards, so raising it really does "
                         f"widen the scan. A cap that cuts is disclosed (D-037).")
    ps.add_argument("--archive", dest="use_archive", action="store_true",
                    help="when a page publishes no deadline, read its ARCHIVED copies "
                         "(Wayback) from past years and project roughly when the next cycle "
                         "opens. Never presented as a deadline - it lands in the profile as "
                         "a 'watch' projection with the years it came from, and it refuses "
                         "outright below three archived cycles.")
    ps.add_argument("--compare-to", dest="compare_to", default=None, metavar="PATH",
                    help="a previous scan's .json export (the sibling of its dashboard). The "
                         "new export carries a 'delta' block - new and removed professors, "
                         "changed fields, recruiting signals to review, newly published "
                         "deadlines - so a re-scan tells you what MOVED instead of asking you "
                         "to re-read every row.")
    ps.add_argument("--institution-types", dest="institution_types", default=None,
                    metavar="T,T",
                    help="which ROR organisation types to scan, comma-separated (default "
                         "education). Supervision is not only at universities: "
                         "'facility' is research institutes and national labs, 'healthcare' "
                         "is teaching hospitals, 'government' is state research agencies, "
                         "'nonprofit' is independent institutes, 'company' is industrial "
                         "labs. Pass 'all' for every type. Valid: "
                         + ", ".join(ror_mod.KNOWN_TYPES) + ".")
    ps.add_argument("--all-institution-types", dest="all_institution_types",
                    action="store_true",
                    help="shorthand for --institution-types all.")
    ps.add_argument("--render-all", dest="render_all", action="store_true",
                    help="read EVERY deep-dive page with Chromium instead of only the pages "
                         "that fetched as a login wall or JavaScript shell. Slower and needs "
                         "Playwright; without it the fetched text is used, never a fake wall.")
    ps.add_argument("--crawl", action="store_true",
                    help="from each professor's page, also read the pages it links to that "
                         "look like 'join the group' or 'vacancies' — where a recruiting "
                         "sentence actually lives. Bounded: depth 2, same host, "
                         f"{sitecrawl.MAX_PAGES} pages max, and it stops as soon as every "
                         "field has an answer.")
    ps.add_argument("--ignore-robots", dest="ignore_robots", action="store_true",
                    help="do NOT enforce robots.txt. Off by default. robots.txt is still read "
                         "and the real verdict is stored per source, so the export never "
                         "claims consent that was not given. Sites block the IP that does "
                         "this, and on a campus network that is your IP.")
    ps.add_argument("--concurrency", type=int, default=pool_mod.DEFAULT_MAX_CONCURRENT,
                    metavar="N",
                    help=f"pages rendered at once when --render-all is on "
                         f"(default {pool_mod.DEFAULT_MAX_CONCURRENT}). One host is always "
                         f"read strictly serially however high this goes.")
    ps.set_defaults(func=cmd_scan)

    pm = sub.add_parser("map-field", help="map a free-text field to a hierarchical OpenAlex "
                                          "subject map (D-066) for topic multi-select")
    pm.add_argument("--field", required=True, help="research field free text (e.g. 'causal ML')")
    pm.add_argument("--out", default="output/subject_map.json",
                    help="subject-map JSON output path (default: output/subject_map.json)")
    pm.add_argument("--email", default=None,
                    help="contact email for the OpenAlex polite pool "
                         "(or set SUPERVISORLY_CONTACT_EMAIL)")
    pm.add_argument("--openalex-key", dest="openalex_key", default=None,
                    help="optional OpenAlex premium key (higher limits)")
    pm.set_defaults(func=cmd_map_field)

    pt = sub.add_parser("studio", help="render a subject map as the self-contained Scan Studio "
                                       "plan wizard (D-067): intent, country, universities, "
                                       "topic multi-select, named professors -> plan JSON")
    pt.add_argument("--map", required=True, dest="map",
                    help="subject-map JSON from `map-field` (default output/subject_map.json)")
    pt.add_argument("--out", default="output/studio.html",
                    help="studio HTML output path (default: output/studio.html)")
    pt.set_defaults(func=cmd_studio)

    pb = sub.add_parser("ingest-page",
                        help="store browser-extracted page TEXT as a snapshot (D-064); "
                             "with --entity + --run it also fills that target's fields and "
                             "closes its awaiting_human gap tasks")
    pb.add_argument("--url", required=True, help="the FINAL page url (after redirects)")
    pb.add_argument("--file", required=True,
                    help="staging file holding the in-page extractor's text output")
    pb.add_argument("--db", default="output/supervisorly.sqlite",
                    help="database path (default: output/supervisorly.sqlite - the store a "
                         "default `scan --out output/...` writes; if your scan used a custom "
                         "--out, pass --db <out-dir>/supervisorly.sqlite)")
    pb.add_argument("--snap-root", dest="snap_root", default=None,
                    help="snapshot store root (default: <db-dir>/.cache/snaps)")
    pb.add_argument("--entity", default=None, metavar="KIND:REF",
                    help="fill this target from the page (e.g. professor:a1234567890); "
                         "requires --run")
    pb.add_argument("--run", dest="run", default=None, metavar="RUN_ID",
                    help="the run the entity belongs to; required with --entity")
    pb.set_defaults(func=cmd_ingest_page)

    pmd = sub.add_parser("ingest-md",
                         help="record the claims Claude for Chrome returned for a blocked "
                              "field (D-043) - the receiving end of the 'human_prompt' the "
                              "dashboard hands you. Paste the reply to a file and pass it here")
    pmd.add_argument("--file", required=True,
                     help="file holding the model's reply verbatim ('## field:' Markdown)")
    pmd.add_argument("--db", default="output/supervisorly.sqlite",
                     help="database path (default: output/supervisorly.sqlite - the store a "
                          "default `scan --out output/...` writes)")
    pmd.set_defaults(func=cmd_ingest_md)

    pv = sub.add_parser("serve",
                        help="open the scan wizard in your browser and run scans from it - "
                             "the same engine as `scan`, with every depth control on the page")
    pv.add_argument("--port", type=int, default=8765)
    pv.add_argument("--work-root", dest="work_root", default="output/jobs",
                    help="root for job working dirs + the job store (default: output/jobs)")
    pv.add_argument("--no-open", dest="no_open", action="store_true",
                    help="do not open a browser window; just print the URL")
    pv.set_defaults(func=cmd_serve)

    pr = sub.add_parser("reexport", help="rebuild the dashboard from the persisted store "
                                         "(D-029) - e.g. after an ingest-page fill; "
                                         "no fetching")
    pr.add_argument("--db", default="output/supervisorly.sqlite",
                    help="database path (default: output/supervisorly.sqlite - the store a "
                         "default `scan --out output/...` writes)")
    pr.add_argument("--out", default="output/dashboard.html",
                    help="dashboard output path (default: output/dashboard.html)")
    pr.add_argument("--optout", default=None,
                    help="path to an optout.txt suppression list (D-023)")
    pr.set_defaults(func=cmd_reexport)

    pp = sub.add_parser("pace", help="social pacing gate — run before every browser page "
                                     "(D-065); exit 0 = ALLOW, 3 = DENY")
    pp.add_argument("--host", help="page host being considered (e.g. x.com)")
    pp.add_argument("--abort", nargs="?", const="", default=None, metavar="REASON",
                    help="latch the host aborted (captcha/soft-block/login redirect)")
    pp.add_argument("--reset", nargs="?", const="all", default=None, metavar="HOST",
                    help="clear pacing state for HOST, or all hosts when omitted")
    pp.add_argument("--state", default=None,
                    help="pacing state path (default: ~/.supervisorly/pacing_state.json)")
    pp.set_defaults(func=cmd_pace)

    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
